"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {MapPin,Search,Clock3,Navigation,Building2,Plus} from "lucide-react";
type S={id:string;name:string;operator_name:string|null;address:string;city:string|null;state:string|null;status:string;price_per_scm:number|null;queue_minutes:number|null;open_now:boolean|null;is_demo:boolean;is_verified:boolean;last_verified_at:string|null};
const labels:Record<string,string>={available:"Available",low_supply:"Low supply",out_of_gas:"Out of gas",offline:"Offline",unknown:"Unknown"};
export default function Stations(){
 const [items,setItems]=useState<S[]>([]),[q,setQ]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{const x=new URLSearchParams(window.location.search).get("q");if(x)setQ(x);createClient().from("stations").select("id,name,operator_name,address,city,state,status,price_per_scm,queue_minutes,open_now,is_demo,is_verified,last_verified_at").eq("registration_status","approved").then(({data})=>{setItems((data||[]) as S[]);setLoading(false)})},[]);
 const shown=useMemo(()=>items.filter(s=>(s.name+" "+s.address+" "+(s.city||"")+" "+(s.state||"")+" "+(s.operator_name||"")).toLowerCase().includes(q.toLowerCase())),[items,q]);
 return <main><header><Link href="/" className="brand"><span className="mark">x</span><div><b>CNGx</b><small>Station network</small></div></Link><nav className="topNav"><Link href="/stations">Find CNG</Link><Link href="/trip">Trip planner</Link><Link href="/marketplace">Marketplace</Link><Link href="/services">Services</Link></nav><div className="headerActions"><BackButton fallback="/"/><Link href="/register-station" className="primary"><Plus size={17}/> Register station</Link></div></header>
 <section className="networkIntro"><div className="eyebrow"><Navigation size={14}/> CNGx station network</div><h1>Find CNG near your route.</h1><p>Search the approved network and compare current availability, price, queue and verification information before you travel.</p></section>
 <section className="stationExplorer"><div className="stationToolbar"><div className="stationSearch"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search station, city, state or operator"/></div><span className="stationCount">{loading?"Loading network…":shown.length+" station"+(shown.length===1?"":"s")+" found"}</span></div>
 <div className="stationLayout"><div className="stationList">{loading?<div className="loadingState">Loading approved CNG stations…</div>:shown.map(s=><article className="stationResult" key={s.id}><div className="stationResultHead"><div><div className="cardBadges"><span className={"status "+s.status}>{labels[s.status]||s.status}</span>{s.is_demo&&<span className="demo">Demo data</span>}{s.is_verified&&<span className="verifiedBadge">Verified</span>}</div><h3>{s.name}</h3></div></div><p className="stationAddress"><MapPin size={16}/>{s.address}{s.city?", "+s.city:""}{s.state?", "+s.state:""}</p><div className="stationMiniMetrics"><div><small>Price / SCM</small><b>{s.price_per_scm!=null?"₦"+s.price_per_scm:"Not reported"}</b></div><div><small>Queue</small><b>{s.queue_minutes!=null?s.queue_minutes+" min":"Unknown"}</b></div><div><small>Updated</small><b>{s.last_verified_at?new Date(s.last_verified_at).toLocaleDateString():"Unverified"}</b></div></div><div className="stationActions"><Link className="primary" href={"/stations/"+s.id}>View station</Link><button className="secondary" onClick={()=>window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.address),"_blank")}><Navigation size={16}/> Directions</button></div></article>)}{!loading&&!shown.length&&<div className="emptyBox"><h2>No stations match this search</h2><p className="muted">Try another location or clear your search. Only stations approved for the CNGx network appear here.</p><button className="secondary" onClick={()=>setQ("")}>Clear search</button></div>}</div>
 <aside className="stationMap" aria-label="Station network overview"><div className="mapGrid"/>{shown.slice(0,3).map((s,i)=><div key={s.id} className={"mapPin p"+(i+1)} title={s.name}><span>{i+1}</span></div>)}<div className="mapOverlay"><h3>Network map</h3><p>This live discovery view is being prepared for full geospatial mapping. For now, each approved station opens directly into navigation from its card.</p></div></aside></div></section></main>
}