"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {ShieldCheck,PackageCheck,Store} from "lucide-react";
const cats=["Compressors","Dispensers","Cascades & Storage","CNG Cylinders","Conversion Kits","Valves & Fittings","Regulators","Hoses & Nozzles","PRMS Equipment","Tube Trailers","Safety Equipment","Testing Equipment","Spare Parts & Accessories"];
export default function Sell(){const [uid,setUid]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{createClient().auth.getUser().then(({data})=>{if(!data.user)location.href="/auth";else setUid(data.user.id)})},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMsg("");const db=createClient(),fd=new FormData(e.currentTarget);let {data:seller}=await db.from("marketplace_sellers").select("id").eq("user_id",uid).maybeSingle();if(!seller){const r=await db.from("marketplace_sellers").insert({user_id:uid,business_name:String(fd.get("business_name")),phone:String(fd.get("phone")),email:String(fd.get("email")),city:String(fd.get("city")),state:String(fd.get("state"))}).select("id").single();seller=r.data;if(r.error){setMsg(r.error.message);setBusy(false);return}}const {error}=await db.from("marketplace_listings").insert({seller_id:seller!.id,title:String(fd.get("title")),category:String(fd.get("category")),condition:String(fd.get("condition")),brand:String(fd.get("brand")),model:String(fd.get("model")),description:String(fd.get("description")),image_url:String(fd.get("image_url")||"")||null,certification:String(fd.get("certification")||"")||null,quantity:Math.max(1,Number(fd.get("quantity")||1)),city:String(fd.get("city")),state:String(fd.get("state")),price:fd.get("price")?Number(fd.get("price")):null,price_on_request:!fd.get("price"),status:"pending"});setMsg(error?error.message:"Listing submitted. Earthoc will review it before publication.");if(!error)e.currentTarget.reset();setBusy(false)}
return <main><header><Link href="/marketplace" className="brand"><span className="mark">x</span><div><b>CNGx</b><small>Seller centre</small></div></Link><BackButton fallback="/marketplace"/></header>
<section className="marketHero"><div className="eyebrow"><Store size={15}/> Seller centre</div><h1>Put your CNG equipment in front of serious buyers.</h1><p>Create a supplier profile and submit equipment for moderated publication. Seller verification and equipment review remain separate trust signals.</p><div className="marketTrustRow"><span><ShieldCheck/> Moderated seller</span><span><PackageCheck/> Equipment review</span><span>Request-quote ready</span></div></section>
<section className="businessGrid"><div className="businessIntro"><span className="eyebrow">LISTING WORKFLOW</span><h2>One submission. Clear review status.</h2><p>Give buyers enough technical and commercial information to understand what you are offering. Earthoc reviews submissions before they become public.</p><div className="businessSteps"><div><b>01</b><span>Create or confirm your seller identity.</span></div><div><b>02</b><span>Add equipment details, location and certification where available.</span></div><div><b>03</b><span>Submit for review and track enquiries from your seller dashboard.</span></div></div></div>
<form className="businessForm" onSubmit={submit}><label>Business / seller name<input name="business_name" required/></label><label>Phone<input name="phone" required/></label><label>Email<input name="email" type="email" required/></label><label>Product title<input name="title" required/></label><label>Brand<input name="brand"/></label><label>Model<input name="model"/></label><label>Category<select name="category">{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>Condition<select name="condition"><option value="new">New</option><option value="used">Used</option><option value="refurbished">Refurbished</option></select></label><label>City<input name="city" required/></label><label>State<input name="state" required/></label><label>Quantity<input name="quantity" type="number" min={1} required/></label><label>Price in naira<input name="price" type="number" min={0} placeholder="Leave blank for Request Quote"/></label><label className="wide">Product image URL<input name="image_url" placeholder="Optional public image link"/></label><label className="wide">Certification / standard<input name="certification" placeholder="Optional — e.g. applicable manufacturer or technical standard"/></label><label className="wide">Description<textarea name="description" required placeholder="Describe specification, capacity, condition, included components and other buyer-relevant details."/></label><div className="formSummary wide"><ShieldCheck size={17}/> Submission is reviewed before public publication.</div><button className="primary wide" disabled={busy}>{busy?"Submitting…":"Submit equipment for review"}</button>{msg&&<div className="authMsg wide">{msg}</div>}</form></section></main>}