"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {Store,PackageCheck,Inbox,Plus,ShieldCheck} from "lucide-react";
export default function Seller(){const [items,setItems]=useState<any[]>([]),[seller,setSeller]=useState<any>(null),[enquiries,setEnquiries]=useState<any[]>([]);useEffect(()=>{const db=createClient();db.auth.getUser().then(async({data})=>{if(!data.user){location.href="/auth";return}const {data:s}=await db.from("marketplace_sellers").select("*").eq("user_id",data.user.id).maybeSingle();setSeller(s);if(s){const {data:l}=await db.from("marketplace_listings").select("id,title,status,created_at").eq("seller_id",s.id).order("created_at",{ascending:false});setItems(l||[]);const ids=(l||[]).map((z:any)=>z.id);if(ids.length){const {data:e}=await db.from("marketplace_enquiries").select("id,message,phone,status,created_at,marketplace_listings(title)").in("listing_id",ids);setEnquiries(e||[])}}})},[]);
return <main><header><Link href="/marketplace" className="brand"><span className="mark">G</span><div><b>GasLink Seller</b><small>Marketplace workspace</small></div></Link><div className="headerActions">{seller&&<Link className="primary" href="/marketplace/sell"><Plus size={17}/> Add listing</Link>}<BackButton fallback="/marketplace"/></div></header>
<section className="operatorHero"><div><div className="eyebrow"><Store size={15}/> Seller workspace</div><h1>Manage your CNG marketplace presence.</h1><p>Track verification, equipment submissions and buyer interest from one place.</p></div>{seller&&<div className="operatorHeroStat"><small>Seller status</small><strong style={{fontSize:24,textTransform:"capitalize"}}>{seller.verification_status}</strong><span><ShieldCheck size={14}/> Earthoc moderation</span></div>}</section>
<section className="adminWrap operatorWrap">{seller?<><div className="adminStats"><div><PackageCheck/><b>{items.length}</b><span>Total listings</span></div><div><ShieldCheck/><b>{items.filter(x=>x.status==="approved").length}</b><span>Approved</span></div><div><Inbox/><b>{enquiries.length}</b><span>Buyer enquiries</span></div><div><Store/><b>{items.filter(x=>x.status==="pending").length}</b><span>Awaiting review</span></div></div>
<h2 className="adminSectionTitle">Your equipment <span>Publication pipeline</span></h2><div className="adminList">{items.map(x=><div key={x.id}><b>{x.title}</b><span>Status: {x.status} · Submitted {new Date(x.created_at).toLocaleDateString()}</span></div>)}{!items.length&&<div className="emptyBox"><h2>No equipment listed yet</h2><p className="muted">Create your first equipment listing and submit it for review.</p><Link className="primary" href="/marketplace/sell">Create first listing</Link></div>}</div>
<h2 className="adminSectionTitle">Buyer enquiries <span>Commercial interest</span></h2><div className="adminList">{enquiries.map((e:any)=><div key={e.id}><b>{e.marketplace_listings?.title||"Listing enquiry"}</b><span>{e.phone||"No phone"} · {e.status}</span><p>{e.message}</p></div>)}{!enquiries.length&&<div className="emptyBox"><Inbox/><h2>No buyer enquiries yet</h2><p className="muted">New enquiries on your listings will appear here.</p></div>}</div></>:<div className="emptyBox" style={{maxWidth:760,margin:"20px auto",textAlign:"center",padding:48}}><Store size={36}/><h2>Build your seller presence on GasLink</h2><p className="muted">Your seller profile is created with your first equipment submission. After review, approved listings can be discovered by CNG buyers.</p><Link className="primary" href="/marketplace/sell">Create first listing</Link></div>}</section></main>}