"use client";import {useEffect,useState} from "react";import Link from "next/link";import BackButton from "@/components/BackButton";import {createClient} from "@/lib/supabase/client";
export default function Admin(){const [ok,setOk]=useState<boolean|null>(null),[data,setData]=useState<any>({claims:[],reports:[],sellers:[],listings:[],providers:[],offerings:[],business:[]});async function load(){const db=createClient(),{data:{user}}=await db.auth.getUser();if(!user){location.href="/auth";return}const {data:p}=await db.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="admin"){setOk(false);return}setOk(true);const [claims,reports,sellers,listings,providers,offerings,business]=await Promise.all([db.from("station_claims").select("id,status,business_name,phone,stations(name)").order("created_at",{ascending:false}),db.from("station_reports").select("id,status,is_moderated,stations(name)").order("created_at",{ascending:false}),db.from("marketplace_sellers").select("*").order("created_at",{ascending:false}),db.from("marketplace_listings").select("id,title,status,category,seller_id").order("created_at",{ascending:false}),db.from("service_providers").select("*").order("created_at",{ascending:false}),db.from("service_offerings").select("id,title,status,category,provider_id").order("created_at",{ascending:false}),db.from("business_enquiries").select("*").order("created_at",{ascending:false})]);setData({claims:claims.data||[],reports:reports.data||[],sellers:sellers.data||[],listings:listings.data||[],providers:providers.data||[],offerings:offerings.data||[],business:business.data||[]})}useEffect(()=>{load()},[]);
async function rpc(fn:string,id:string,status:string){const names:any={admin_marketplace_seller:"p_id",admin_marketplace_listing:"p_id",admin_service_provider:"p_id",admin_service_offering:"p_id"};const {error}=await createClient().rpc(fn,{[names[fn]]:id,p_status:status});if(error)alert(error.message);else load()}async function claim(id:string,a:boolean){const {error}=await createClient().rpc("approve_station_claim",{p_claim_id:id,p_approve:a});if(error)alert(error.message);else load()}async function moderate(id:string){await createClient().from("station_reports").update({is_moderated:true}).eq("id",id);load()}
const buttons=(fn:string,id:string,status:string,verified="approved")=>status==="pending"?<p><button className="primary" onClick={()=>rpc(fn,id,verified)}>Approve</button> <button className="secondary" onClick={()=>rpc(fn,id,"rejected")}>Reject</button></p>:null;
if(ok===null)return <main className="panel">Checking Earthoc Admin access…</main>;if(!ok)return <main className="panel"><h1>Admin access required</h1><Link href="/" className="primary">Return to GasLink</Link></main>;
return <main><header><Link href="/" className="brand"><span className="mark">G</span><div><b>GasLink Admin</b><small>Earthoc Gas</small></div></Link><BackButton fallback="/dashboard"/></header><section className="adminWrap"><h1>GasLink operations</h1><div className="adminStats"><div><b>{data.claims.length}</b><span>Station claims</span></div><div><b>{data.listings.filter((x:any)=>x.status==="pending").length}</b><span>Listings pending</span></div><div><b>{data.providers.filter((x:any)=>x.verification_status==="pending").length}</b><span>Providers pending</span></div><div><b>{data.business.length}</b><span>Business leads</span></div></div>
<h2>Marketplace sellers</h2><div className="adminList">{data.sellers.length?data.sellers.map((x:any)=><div key={x.id}><b>{x.business_name}</b><span>{x.city||""} {x.state||""} · {x.verification_status}</span>{buttons("admin_marketplace_seller",x.id,x.verification_status,"verified")}</div>):<p className="muted">No sellers yet.</p>}</div>
<h2>Marketplace listings</h2><div className="adminList">{data.listings.length?data.listings.map((x:any)=><div key={x.id}><b>{x.title}</b><span>{x.category} · {x.status}</span>{buttons("admin_marketplace_listing",x.id,x.status)}</div>):<p className="muted">No listings yet.</p>}</div>
<h2>Service providers</h2><div className="adminList">{data.providers.length?data.providers.map((x:any)=><div key={x.id}><b>{x.business_name}</b><span>{x.provider_type} · {x.verification_status}</span>{buttons("admin_service_provider",x.id,x.verification_status,"verified")}</div>):<p className="muted">No providers yet.</p>}</div>
<h2>Service offerings</h2><div className="adminList">{data.offerings.length?data.offerings.map((x:any)=><div key={x.id}><b>{x.title}</b><span>{x.category} · {x.status}</span>{buttons("admin_service_offering",x.id,x.status)}</div>):<p className="muted">No services yet.</p>}</div>
<h2>CNG for Business enquiries</h2><div className="adminList">{data.business.length?data.business.map((x:any)=><div key={x.id}><b>{x.company_name} · {x.enquiry_type}</b><span>{x.contact_name} · {x.phone||x.email||"No contact"}{x.estimated_daily_scm?" · "+x.estimated_daily_scm+" SCM/day":""}</span><p>{x.message}</p></div>):<p className="muted">No business enquiries yet.</p>}</div>
<h2>Station claims</h2><div className="adminList">{data.claims.length?data.claims.map((x:any)=><div key={x.id}><b>{x.business_name||"Unnamed operator"}</b><span>{x.stations?.name||"Station"} · {x.status}</span>{x.status==="pending"&&<p><button className="primary" onClick={()=>claim(x.id,true)}>Approve</button> <button className="secondary" onClick={()=>claim(x.id,false)}>Reject</button></p>}</div>):<p className="muted">No claims yet.</p>}</div>
<h2>Community reports</h2><div className="adminList">{data.reports.length?data.reports.map((x:any)=><div key={x.id}><b>{x.stations?.name||"Station"} · {x.status||"unknown"}</b><span>{x.is_moderated?"Reviewed":"Awaiting review"}</span>{!x.is_moderated&&<p><button className="primary" onClick={()=>moderate(x.id)}>Mark reviewed</button></p>}</div>):<p className="muted">No reports yet.</p>}</div></section></main>}