"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {Calculator,Fuel,Gauge,TrendingDown,Wallet,Info,ArrowRight} from "lucide-react";
const money=(n:number)=>"₦"+Math.max(0,n||0).toLocaleString(undefined,{maximumFractionDigits:0});
export default function Savings(){
 const [km,setKm]=useState(1500),[petrol,setPetrol]=useState(1100),[pkm,setPkm]=useState(10),[cng,setCng]=useState(520),[ckm,setCkm]=useState(11);
 const v=(n:number)=>Number.isFinite(n)&&n>0?n:0;
 const calc=useMemo(()=>{const d=v(km),pe=v(pkm),ce=v(ckm),pp=v(petrol),cp=v(cng);const petrolCost=pe?d/pe*pp:0,cngCost=ce?d/ce*cp:0,saving=Math.max(0,petrolCost-cngCost),pct=petrolCost?saving/petrolCost*100:0;return{petrolCost,cngCost,saving,pct,annual:saving*12}},[km,petrol,pkm,cng,ckm]);
 return <main><header><Link href="/" className="brand"><span className="mark">x</span><div><b>CNGx</b><small>Savings calculator</small></div></Link><nav className="topNav"><Link href="/stations">Find CNG</Link><Link href="/trip">Trip planner</Link><Link href="/savings">Savings</Link></nav><div className="headerActions"><BackButton fallback="/dashboard"/></div></header>
 <section className="savingsHero"><div><span className="eyebrow"><Calculator size={14}/> Cost intelligence</span><h1>See what switching to CNG could save.</h1><p>Compare estimated monthly petrol and CNG fuel costs using your own driving pattern, prices and vehicle efficiency.</p></div><div className="savingsHeroMetric"><small>Estimated monthly saving</small><strong>{money(calc.saving)}</strong><span>{calc.pct.toFixed(0)}% lower estimated fuel cost</span></div></section>
 <section className="savingsWorkspace"><div className="savingsFormCard"><div className="sectionTitle"><div><span className="eyebrow">Your assumptions</span><h2>Vehicle & fuel inputs</h2></div><Info size={20}/></div><div className="savingsInputs"><label><span>Monthly distance</span><div className="inputWithIcon"><Gauge/><input type="number" min="1" value={km} onChange={e=>setKm(+e.target.value)}/><b className="inputSuffix">km</b></div></label><label><span>Petrol price</span><div className="inputWithIcon"><Fuel/><input type="number" min="1" value={petrol} onChange={e=>setPetrol(+e.target.value)}/><b className="inputSuffix">₦/L</b></div></label><label><span>Petrol efficiency</span><div className="inputWithIcon"><Gauge/><input type="number" min=".1" step=".1" value={pkm} onChange={e=>setPkm(+e.target.value)}/><b className="inputSuffix">km/L</b></div></label><label><span>CNG price</span><div className="inputWithIcon"><Fuel/><input type="number" min="1" value={cng} onChange={e=>setCng(+e.target.value)}/><b className="inputSuffix">₦/SCM</b></div></label><label><span>CNG efficiency</span><div className="inputWithIcon"><Gauge/><input type="number" min=".1" step=".1" value={ckm} onChange={e=>setCkm(+e.target.value)}/><b className="inputSuffix">km/SCM</b></div></label></div><p className="calculatorNote"><Info size={15}/> Estimates depend on the values you enter and do not include conversion, maintenance or financing costs.</p></div>
 <div className="savingsResults"><div className="resultLead"><span className="eyebrow">Estimated outcome</span><Wallet/><small>Monthly saving</small><strong>{money(calc.saving)}</strong><span className="savingPercent"><TrendingDown size={16}/>{calc.pct.toFixed(1)}% estimated reduction</span></div><div className="costCompare"><div><span>Petrol / month</span><b>{money(calc.petrolCost)}</b><div className="costBar petrolBar"></div></div><ArrowRight/><div><span>CNG / month</span><b>{money(calc.cngCost)}</b><div className="costBar cngBar" style={{width:(calc.petrolCost?Math.min(100,calc.cngCost/calc.petrolCost*100):0)+"%"}}></div></div></div><div className="annualSaving"><div><small>Potential annual fuel saving</small><strong>{money(calc.annual)}</strong></div><Link href="/stations" className="primary">Find CNG stations <ArrowRight size={16}/></Link></div></div></section>
 <section className="savingsExplain"><div><span className="eyebrow">How this estimate works</span><h2>A transparent comparison, not a promise.</h2></div><div className="explainGrid"><article><b>1</b><h3>Distance</h3><p>Your monthly kilometres determine estimated fuel consumption.</p></article><article><b>2</b><h3>Efficiency</h3><p>Petrol km/L and CNG km/SCM are calculated separately.</p></article><article><b>3</b><h3>Fuel price</h3><p>Each consumption estimate is multiplied by the price you provide.</p></article></div></section></main>
}