"use client";
import {FormEvent,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import Link from "next/link";import BackButton from "@/components/BackButton";
export default function AuthPage(){
 const [mode,setMode]=useState<"signin"|"signup">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[needsConfirm,setNeedsConfirm]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");const s=createClient();
  if(mode==="signup"){const {error}=await s.auth.signUp({email,password,options:{data:{full_name:name}}});setNeedsConfirm(!error);setMsg(error?error.message:"Account created. We sent you a confirmation link by email.");}
  else {const {error}=await s.auth.signInWithPassword({email,password});if(error){const confirm=error.message.toLowerCase().includes("email not confirmed");setNeedsConfirm(confirm);setMsg(confirm?"Please confirm your email before signing in. You can resend the confirmation below.":error.message)}else window.location.href="/dashboard";}
  setBusy(false);
 }
 async function resend(){if(!email){setMsg("Enter your email address first.");return}setBusy(true);const {error}=await createClient().auth.resend({type:"signup",email});setMsg(error?error.message:"Confirmation email sent again. Check your inbox and spam folder.");setBusy(false)}
 return <main className="authWrap"><section className="authCard"><BackButton/><div className="brand authBrand"><span className="mark">G</span><div><b>GasLink</b><small>by Earthoc Gas</small></div></div><h1>{mode==="signin"?"Welcome back":"Create your GasLink account"}</h1><p className="muted">Drivers can browse and report station conditions. Approved operators manage their stations.</p><form onSubmit={submit}>{mode==="signup"&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="primary" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form>{msg&&<div className="authMsg">{msg}</div>}{needsConfirm&&<button className="resendBtn" disabled={busy} onClick={resend}>Resend confirmation email</button>}<button className="switch" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setMsg("")}}>{mode==="signin"?"New to GasLink? Create account":"Already have an account? Sign in"}</button></section></main>
}