"use client";
import {useEffect,useMemo,useState} from "react";
import {MapPin,Search,Route,Fuel,Gauge,UserRound,Calculator,Navigation,Clock3,ShieldCheck} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {useRouter} from "next/navigation";
type Station={id:string;name:string;operator_name:string|null;address:string;city:string|null;state:string|null;status:string;price_per_scm:number|null;queue_minutes:number|null;open_now:boolean|null;is_demo:boolean;is_verified:boolean};
const fallback:Station[]=[{id:"ph",name:"Demo CNG Station - Port Harcourt",operator_name:"Demo Operator",address:"Aba Road corridor, Port Harcourt",city:"Port Harcourt",state:"Rivers",status:"available",price_per_scm:520,queue_minutes:15,open_now:true,is_demo:true,is_verified:false},{id:"aba",name:"Demo CNG Station - Aba",operator_name:"Demo Operator",address:"Aba industrial corridor",city:"Aba",state:"Abia",status:"low_supply",price_per_scm:510,queue_minutes:30,open_now:true,is_demo:true,is_verified:false},{id:"owerri",name:"Demo CNG Station - Owerri",operator_name:"Demo Operator",address:"Owerri urban corridor",city:"Owerri",state:"Imo",status:"unknown",price_per_scm:null,queue_minutes:null,open_now:null,is_demo:true,is_verified:false}];
const labels:Record<string,string>={available:"Available",low_supply:"Low supply",out_of_gas:"Out of gas",offline:"Offline",unknown:"Unknown"};
export default function Home(){
 const router=useRouter();
 const [stations,setStations]=useState<Station[]>(fallback),[q,setQ]=useState(""),[tab,setTab]=useState("home"); const [fuelPrice,setFuelPrice]=useState(1100),[monthlyKm,setMonthlyKm]=useState(1500),[petrolKmL,setPetrolKmL]=useState(10),[cngKmScm,setCngKmScm]=useState(11),[cngPrice,setCngPrice]=useState(520);
 useEffect(()=>{const s=createClient();s.from("stations").select("*").then(({data})=>{if(data?.length)setStations(data as Station[])})},[]);
 const shown=useMemo(()=>stations.filter(s=>(s.name+" "+s.city+" "+s.state).toLowerCase().includes(q.toLowerCase())),[stations,q]); const petrol=monthlyKm/petrolKmL*fuelPrice,cng=monthlyKm/cngKmScm*cngPrice,saving=Math.max(0,petrol-cng);
 return <main><header><div className="brand"><span className="mark">G</span><div><b>GasLink</b><small>by Earthoc Gas</small></div></div><button className="ghost" onClick={()=>router.push("/auth")}><UserRound size={19}/> Sign in</button></header>
 <section className="hero"><div className="eyebrow"><ShieldCheck size={15}/> Nigeria&apos;s CNG access companion</div><h1>Find gas.<br/>Know before you go.</h1><p>Discover CNG stations, check recent supply reports, estimate queues and plan a smarter journey.</p><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, state or station"/><button onClick={()=>setTab("stations")}>Find CNG</button></div><div className="notice"><b>Phase 0 demo:</b> Sample stations and prices are clearly marked. GasLink will not present them as live verified data.</div></section>
 {tab==="home"&&<><section className="quick"><button onClick={()=>setTab("stations")}><MapPin/><b>Find a station</b><span>Availability, price & queue</span></button><button onClick={()=>setTab("trip")}><Route/><b>Plan a trip</b><span>Find refuelling options</span></button><button onClick={()=>setTab("savings")}><Calculator/><b>Calculate savings</b><span>Compare CNG with petrol</span></button><button onClick={()=>router.push("/marketplace")}><Fuel/><b>CNG Marketplace</b><span>Buy & sell CNG equipment</span></button><button onClick={()=>router.push("/services")}><ShieldCheck/><b>CNG Services</b><span>Conversion, maintenance & technical support</span></button></section><Stations rows={shown}/></>}
 {tab==="stations"&&<Stations rows={shown}/>}
 {tab==="trip"&&<section className="panel"><div className="eyebrow"><Navigation size={15}/> Trip planner</div><h2>Plan your CNG journey</h2><p className="muted">Phase 0 uses station discovery rather than paid turn-by-turn routing.</p><label>Starting point<input placeholder="e.g. Port Harcourt"/></label><label>Destination<input placeholder="e.g. Aba"/></label><label>Estimated CNG range (km)<input type="number" defaultValue="250"/></label><button className="primary" onClick={()=>setTab("stations")}>Show refuelling options</button></section>}
 {tab==="savings"&&<section className="panel"><div className="eyebrow"><Gauge size={15}/> Savings calculator</div><h2>What could CNG save you?</h2><div className="grid"><label>Monthly distance (km)<input type="number" value={monthlyKm} onChange={e=>setMonthlyKm(+e.target.value)}/></label><label>Petrol price (₦/L)<input type="number" value={fuelPrice} onChange={e=>setFuelPrice(+e.target.value)}/></label><label>Petrol efficiency (km/L)<input type="number" value={petrolKmL} onChange={e=>setPetrolKmL(+e.target.value)}/></label><label>CNG price (₦/SCM)<input type="number" value={cngPrice} onChange={e=>setCngPrice(+e.target.value)}/></label><label>CNG efficiency (km/SCM)<input type="number" value={cngKmScm} onChange={e=>setCngKmScm(+e.target.value)}/></label></div><div className="result"><span>Estimated monthly saving</span><strong>₦{saving.toLocaleString(undefined,{maximumFractionDigits:0})}</strong><small>Petrol ₦{petrol.toLocaleString(undefined,{maximumFractionDigits:0})} · CNG ₦{cng.toLocaleString(undefined,{maximumFractionDigits:0})}</small></div></section>}
 {tab==="profile"&&<section className="panel"><div className="eyebrow"><UserRound size={15}/> GasLink account</div><h2>Driver, operator or Earthoc admin</h2><p className="muted">Authentication is being connected to the dedicated GasLink backend. Station browsing remains available without an account.</p><button className="primary" onClick={()=>setTab("home")}>Continue browsing</button></section>}
 <nav><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Fuel/>Home</button><button className={tab==="stations"?"active":""} onClick={()=>setTab("stations")}><MapPin/>Stations</button><button className={tab==="trip"?"active":""} onClick={()=>setTab("trip")}><Route/>Trip</button><button className={tab==="savings"?"active":""} onClick={()=>setTab("savings")}><Calculator/>Savings</button><button onClick={()=>router.push("/marketplace")}><Fuel/>Market</button><button onClick={()=>router.push("/services")}><ShieldCheck/>Services</button></nav></main>}
function Stations({rows}:{rows:Station[]}){return <section className="stations"><div className="sectionTitle"><div><span className="eyebrow">CNG network</span><h2>Stations</h2></div><span>{rows.length} found</span></div><div className="cards">{rows.map(s=><article key={s.id}><div className="cardtop"><span className={"status "+s.status}>{labels[s.status]||s.status}</span>{s.is_demo&&<span className="demo">DEMO DATA</span>}</div><h3>{s.name}</h3><button className="viewStation" onClick={()=>location.href="/stations/"+s.id}>View station</button><p><MapPin size={16}/>{s.address}</p><div className="metrics"><div><small>Price / SCM</small><b>{s.price_per_scm?("₦"+s.price_per_scm):"Not reported"}</b></div><div><small>Queue</small><b>{s.queue_minutes!=null?(s.queue_minutes+" min"):"Unknown"}</b></div></div><div className="cardfoot"><span><Clock3 size={15}/>{s.is_verified?"Verified":"Not yet verified"}</span><button onClick={()=>window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.address),"_blank")}>Directions</button></div></article>)}</div></section>}