import type{RoutingProvider}from"./provider";import type{NormalizedRoute,ResolvedPlace,RouteGeometry}from"@/lib/trip/contracts";
const GEOCODE="https://api.mapbox.com/search/geocode/v6/forward";const DIRECTIONS="https://api.mapbox.com/directions/v5/mapbox/driving";
function token(){const value=process.env.MAPBOX_ACCESS_TOKEN;if(!value)throw new Error("Mapbox routing is not configured");return value}
function validCoord(v:unknown):v is[number,number]{return Array.isArray(v)&&v.length>=2&&v.every((n,i)=>i>1||typeof n==="number"&&Number.isFinite(n))&&v[0]>=-180&&v[0]<=180&&v[1]>=-90&&v[1]<=90}
export class MapboxRoutingProvider implements RoutingProvider{readonly name="mapbox";
 async searchPlaces(query:string){if(query.trim().length<3)return[];const u=new URL(GEOCODE);u.searchParams.set("q",query.trim());u.searchParams.set("access_token",token());u.searchParams.set("country","ng");u.searchParams.set("limit","5");u.searchParams.set("autocomplete","true");const r=await fetch(u,{cache:"no-store",signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error("Mapbox place search unavailable");const j=await r.json();return (Array.isArray(j.features)?j.features:[]).flatMap((f:any)=>{const c=f?.geometry?.coordinates;if(!validCoord(c))return[];return[{label:f.properties?.full_address||f.properties?.name||f.place_name||query,coordinate:{longitude:c[0],latitude:c[1]}}]})}
 async resolvePlace(query:string){const list=await this.searchExact(query);return list[0]||null}
 private async searchExact(query:string){const u=new URL(GEOCODE);u.searchParams.set("q",query.trim());u.searchParams.set("access_token",token());u.searchParams.set("country","ng");u.searchParams.set("limit","1");u.searchParams.set("autocomplete","false");const r=await fetch(u,{cache:"no-store",signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error("Mapbox geocoding unavailable");const j=await r.json();return (Array.isArray(j.features)?j.features:[]).flatMap((f:any)=>{const c=f?.geometry?.coordinates;if(!validCoord(c))return[];return[{label:f.properties?.full_address||f.properties?.name||f.place_name||query,coordinate:{longitude:c[0],latitude:c[1]}}]})}
 async route(origin:ResolvedPlace,destination:ResolvedPlace):Promise<NormalizedRoute>{const a=origin.coordinate,b=destination.coordinate;const u=new URL(`${DIRECTIONS}/${a.longitude},${a.latitude};${b.longitude},${b.latitude}`);u.searchParams.set("access_token",token());u.searchParams.set("geometries","geojson");u.searchParams.set("overview","full");u.searchParams.set("steps","false");const r=await fetch(u,{cache:"no-store",signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("Mapbox directions unavailable");const j=await r.json();const x=j?.routes?.[0],g=x?.geometry;if(!x||g?.type!=="LineString"||!Array.isArray(g.coordinates)||g.coordinates.length<2||!g.coordinates.every(validCoord)||!Number.isFinite(x.distance)||!Number.isFinite(x.duration))throw new Error("Malformed Mapbox route");return{geometry:g as RouteGeometry,distanceMeters:x.distance,durationSeconds:x.duration}}
}