import type{PlannedStop,TripFailureReason,TripStation}from"./contracts";
export function effectiveRangeKm(vehicleRangeKm:number,reservePercent:number){if(!Number.isFinite(vehicleRangeKm)||vehicleRangeKm<20||vehicleRangeKm>2000||!Number.isFinite(reservePercent)||reservePercent<0||reservePercent>50)return null;return vehicleRangeKm*(1-reservePercent/100)}
type Result={feasible:boolean;stops:PlannedStop[];alternateStops:PlannedStop[];reason?:TripFailureReason};
export function planStops(stations:TripStation[],routeKm:number,effectiveKm:number):Result{if(!Number.isFinite(routeKm)||routeKm<=0)return{feasible:false,stops:[],alternateStops:[],reason:"INVALID_ROUTE"};if(routeKm<=effectiveKm)return{feasible:true,stops:[],alternateStops:[]};
 const usable=stations.filter(s=>s.routeProgressFraction>0&&s.routeProgressFraction<1&&s.status!=="offline"&&s.status!=="out_of_gas").map(s=>({...s,routeProgressKm:s.routeProgressFraction*routeKm})).sort((a,b)=>a.routeProgressKm-b.routeProgressKm||a.distanceFromRouteMeters-b.distanceFromRouteMeters);
 if(!usable.length)return{feasible:false,stops:[],alternateStops:[],reason:stations.length?"NO_REACHABLE_STATION":"NO_TRUSTED_STATIONS_ON_CORRIDOR"};
 const paths:typeof usable[]=[];const walk=(pos:number,start:number,path:typeof usable)=>{if(paths.length>=8)return;if(routeKm-pos<=effectiveKm){paths.push(path);return}for(let i=start;i<usable.length;i++){const s=usable[i];if(s.routeProgressKm<=pos)continue;if(s.routeProgressKm-pos>effectiveKm)break;walk(s.routeProgressKm,i+1,[...path,s])}};
 walk(0,0,[]);if(!paths.length){let prev=0,maxGap=0;for(const s of usable){maxGap=Math.max(maxGap,s.routeProgressKm-prev);prev=s.routeProgressKm}maxGap=Math.max(maxGap,routeKm-prev);return{feasible:false,stops:[],alternateStops:[],reason:maxGap>effectiveKm?"CORRIDOR_GAP_EXCEEDS_RANGE":"NO_REACHABLE_STATION"}}
 paths.sort((a,b)=>a.length-b.length||a.reduce((n,s)=>n+s.distanceFromRouteMeters,0)-b.reduce((n,s)=>n+s.distanceFromRouteMeters,0));const decorate=(p:typeof usable)=>p.map((s,i)=>({...s,legDistanceKm:s.routeProgressKm-(i?p[i-1].routeProgressKm:0)}));return{feasible:true,stops:decorate(paths[0]),alternateStops:paths[1]?decorate(paths[1]):[]}}
export function trustWarnings(stations:TripStation[]){const out:string[]=[];if(stations.some(s=>s.locationPrecision==="approximate"))out.push("One or more planned stations have approximate coordinates. Confirm the station entrance before departure.");if(stations.some(s=>s.status==="unknown"))out.push("One or more planned stations have unknown current operating status.");return out}