"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import PublicStationTrust from "@/components/PublicStationTrust";
import {createClient} from "@/lib/supabase/client";
import {PUBLIC_STATION_VISIBILITY_OR_FILTER,publicStationDirections} from "@/lib/station-public-visibility";
import {Route,MapPin,Navigation,Gauge,Clock3,Search,ArrowRight,ShieldCheck} from "lucide-react";
type S={
 id:string;name:string;address:string;city:string|null;state:string|null;status:string;price_per_scm:number|null;queue_minutes:number|null;
 last_verified_at:string|null;is_verified:boolean;record_source_type:string|null;record_source_name:string|null;publication_status:string|null;registration_status:string|null;
 latitude:number|null;longitude:number|null;location:unknown|null;location_precision:string|null;
};
const labels:Record<string,string>={available:"Available",low_supply:"Low supply",out_of_gas:"Out of gas",offline:"Offline",unknown:"Unknown"};
export default function Trip(){
 const [from,setFrom]=useState(""),[to,setTo]=useState(""),[range,setRange]=useState("200"),[all,setAll]=useState<S[]>([]),[results,setResults]=useState<S[]>([]),[show,setShow]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{
  createClient().from("stations")
   .select("id,name,address,city,state,status,price_per_scm,queue_minutes,last_verified_at,is_verified,record_source_type,record_source_name,publication_status,registration_status,latitude,longitude,location,location_precision")
   .or(PUBLIC_STATION_VISIBILITY_OR_FILTER)
   .then(({data})=>{setAll((data||[]) as S[]);setLoading(false)});
 },[]);
 function go(e:FormEvent){e.preventDefault();const words=(from+" "+to).toLowerCase().split(/\s+/).filter(x=>x.length>2);const matched=all.filter(s=>words.some(w=>(s.name+" "+s.address+" "+(s.city||"")+" "+(s.state||"")).toLowerCase().includes(w)));setResults(matched.length?matched:all);setShow(true)}
 return <main><header><Link href="/" className="brand"><span className="mark">x</span><div><b>CNGx</b><small>Trip planner</small></div></Link><nav className="topNav"><Link href="/stations">Find CNG</Link><Link href="/trip">Trip planner</Link><Link href="/savings">Savings</Link></nav><div className="headerActions"><BackButton fallback="/dashboard"/></div></header>
 <section className="tripHero"><div className="eyebrow"><Route size={14}/> CNG journey planning</div><h1>Plan the fuel stops before the road.</h1><p>Use CNGx’s public station directory to identify refuelling options around your journey. This is station discovery—not turn-by-turn navigation.</p></section>
 <section className="tripWorkspace"><form className="tripForm" onSubmit={go}><div className="tripFormTitle"><div className="tripIcon"><Navigation/></div><div><h2>Build your journey</h2><p className="muted">Enter your route and expected CNG driving range.</p></div></div><div className="routeInputs"><label><span>Starting point</span><div className="inputWithIcon"><MapPin/><input required value={from} onChange={e=>setFrom(e.target.value)} placeholder="e.g. Port Harcourt"/></div></label><div className="routeConnector"><ArrowRight/></div><label><span>Destination</span><div className="inputWithIcon"><MapPin/><input required value={to} onChange={e=>setTo(e.target.value)} placeholder="e.g. Aba"/></div></label></div><label><span>Estimated vehicle CNG range</span><div className="inputWithIcon"><Gauge/><input type="number" min="1" max="2000" required value={range} onChange={e=>setRange(e.target.value)} /><b className="inputSuffix">km</b></div></label><button className="primary tripSubmit" disabled={loading}><Search size={17}/>{loading?"Loading station network…":"Find refuelling options"}</button></form>
 <aside className="tripGuidance"><span className="eyebrow">Before you travel</span><h2>Route confidence starts with trustworthy station evidence.</h2><div className="guideItem"><ShieldCheck/><div><b>Check verification</b><span>Directory provenance and CNGx verification are separate signals.</span></div></div><div className="guideItem"><Clock3/><div><b>Watch queue and supply</b><span>Conditions can change quickly at CNG stations.</span></div></div><div className="guideItem"><Gauge/><div><b>Keep range margin</b><span>Do not plan a journey at the absolute limit of your vehicle range.</span></div></div></aside></section>
 {show&&<section className="tripResults"><div className="tripResultsHead"><div><span className="eyebrow">Suggested directory stops</span><h2>{from} <ArrowRight size={22}/> {to}</h2><p>Range entered: <b>{range} km</b>. These are text/location matches within the public CNGx directory; confirm road distance and live conditions before departure.</p></div><span className="stationCount">{results.length} option{results.length===1?"":"s"}</span></div><div className="tripResultGrid">{results.length?results.map((s,i)=>{const directions=publicStationDirections(s);return <article className="tripResultCard" key={s.id}><div className="tripStopNumber">{i+1}</div><div className="cardBadges"><span className={"status "+s.status}>{labels[s.status]||s.status}</span>{s.is_verified&&<span className="verifiedBadge">Verified</span>}</div><h3>{s.name}</h3><p className="stationAddress"><MapPin size={15}/>{s.address}{s.city?", "+s.city:""}{s.state?", "+s.state:""}</p><PublicStationTrust recordSourceType={s.record_source_type} recordSourceName={s.record_source_name} isVerified={s.is_verified} status={s.status} locationPrecision={s.location_precision}/><div className="stationMiniMetrics"><div><small>Price / SCM</small><b>{s.price_per_scm!=null?"₦"+s.price_per_scm:"Unknown"}</b></div><div><small>Queue</small><b>{s.queue_minutes!=null?s.queue_minutes+" min":"Unknown"}</b></div></div><div className="stationActions"><Link className="primary" href={"/stations/"+s.id}>View station</Link><button className="secondary" onClick={()=>window.open(directions.url,"_blank")}><Navigation size={16}/> {directions.label}</button></div></article>}):<div className="emptyBox"><h2>No public stations found</h2><p className="muted">Try broader city or state names, or browse the complete public station directory.</p><Link href="/stations" className="primary">Browse Find CNG</Link></div>}</div></section>}</main>
}
