"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {Route,MapPin,Navigation,Gauge,Clock3,Search,ArrowRight,ShieldCheck} from "lucide-react";
type S={id:string;name:string;address:string;city:string|null;state:string|null;status:string;price_per_scm:number|null;queue_minutes:number|null;last_verified_at:string|null;is_verified:boolean};
const labels:Record<string,string>={available:"Available",low_supply:"Low supply",out_of_gas:"Out of gas",offline:"Offline",unknown:"Unknown"};
export default function Trip(){
 const [from,setFrom]=useState(""),[to,setTo]=useState(""),[range,setRange]=useState("200"),[all,setAll]=useState<S[]>([]),[results,setResults]=useState<S[]>([]),[show,setShow]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{createClient().from("stations").select("id,name,address,city,state,status,price_per_scm,queue_minutes,last_verified_at,is_verified").eq("registration_status","approved").then(({data})=>{setAll((data||[]) as S[]);setLoading(false)})},[]);
 function go(e:FormEvent){e.preventDefault();const words=(from+" "+to).toLowerCase().split(/\s+/).filter(x=>x.length>2);const matched=all.filter(s=>words.some(w=>(s.name+" "+s.address+" "+(s.city||"")+" "+(s.state||"")).toLowerCase().includes(w)));setResults(matched.length?matched:all);setShow(true)}
 return <main><header><Link href="/" className="brand"><span className="mark">G</span><div><b>GasLink</b><small>Trip planner</small></div></Link><nav className="topNav"><Link href="/stations">Find CNG</Link><Link href="/trip">Trip planner</Link><Link href="/savings">Savings</Link></nav><div className="headerActions"><BackButton fallback="/dashboard"/></div></header>
 <section className="tripHero"><div className="eyebrow"><Route size={14}/> CNG journey planning</div><h1>Plan the fuel stops before the road.</h1><p>Use GasLink’s approved station network to identify refuelling options around your journey. This is station discovery—not turn-by-turn navigation.</p></section>
 <section className="tripWorkspace"><form className="tripForm" onSubmit={go}><div className="tripFormTitle"><div className="tripIcon"><Navigation/></div><div><h2>Build your journey</h2><p className="muted">Enter your route and expected CNG driving range.</p></div></div><div className="routeInputs"><label><span>Starting point</span><div className="inputWithIcon"><MapPin/><input required value={from} onChange={e=>setFrom(e.target.value)} placeholder="e.g. Port Harcourt"/></div></label><div className="routeConnector"><ArrowRight/></div><label><span>Destination</span><div className="inputWithIcon"><MapPin/><input required value={to} onChange={e=>setTo(e.target.value)} placeholder="e.g. Aba"/></div></label></div><label><span>Estimated vehicle CNG range</span><div className="inputWithIcon"><Gauge/><input type="number" min="1" max="2000" required value={range} onChange={e=>setRange(e.target.value)} /><b className="inputSuffix">km</b></div></label><button className="primary tripSubmit" disabled={loading}><Search size={17}/>{loading?"Loading station network…":"Find refuelling options"}</button></form>
 <aside className="tripGuidance"><span className="eyebrow">Before you travel</span><h2>Route confidence starts with fresh station data.</h2><div className="guideItem"><ShieldCheck/><div><b>Check verification</b><span>Prioritise recently verified station information.</span></div></div><div className="guideItem"><Clock3/><div><b>Watch queue and supply</b><span>Conditions can change quickly at CNG stations.</span></div></div><div className="guideItem"><Gauge/><div><b>Keep range margin</b><span>Do not plan a journey at the absolute limit of your vehicle range.</span></div></div></aside></section>
 {show&&<section className="tripResults"><div className="tripResultsHead"><div><span className="eyebrow">Suggested network stops</span><h2>{from} <ArrowRight size={22}/> {to}</h2><p>Range entered: <b>{range} km</b>. These results match locations in GasLink’s approved network; confirm road distance and live conditions before departure.</p></div><span className="stationCount">{results.length} option{results.length===1?"":"s"}</span></div><div className="tripResultGrid">{results.length?results.map((s,i)=><article className="tripResultCard" key={s.id}><div className="tripStopNumber">{i+1}</div><div className="cardBadges"><span className={"status "+s.status}>{labels[s.status]||s.status}</span>{s.is_verified&&<span className="verifiedBadge">Verified</span>}</div><h3>{s.name}</h3><p className="stationAddress"><MapPin size={15}/>{s.address}{s.city?", "+s.city:""}{s.state?", "+s.state:""}</p><div className="stationMiniMetrics"><div><small>Price / SCM</small><b>{s.price_per_scm!=null?"₦"+s.price_per_scm:"Unknown"}</b></div><div><small>Queue</small><b>{s.queue_minutes!=null?s.queue_minutes+" min":"Unknown"}</b></div></div><div className="stationActions"><Link className="primary" href={"/stations/"+s.id}>View station</Link><button className="secondary" onClick={()=>window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.address),"_blank")}><Navigation size={16}/> Directions</button></div></article>):<div className="emptyBox"><h2>No approved stations found</h2><p className="muted">Try broader city or state names, or browse the complete approved station network.</p><Link href="/stations" className="primary">Browse Find CNG</Link></div>}</div></section>}</main>
}