"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {MapPin,Navigation,Clock3,ShieldCheck,Gauge,MessageSquare,Building2,CheckCircle2} from "lucide-react";
type S={id:string;name:string;operator_name:string|null;address:string;city:string|null;state:string|null;status:string;price_per_scm:number|null;queue_minutes:number|null;open_now:boolean|null;opening_hours:string|null;vehicle_compatibility:string[]|null;is_demo:boolean;is_verified:boolean;last_verified_at:string|null};
type R={id:string;status:string;price_per_scm:number|null;queue_minutes:number|null;created_at:string};
const labels:Record<string,string>={available:"Available",low_supply:"Low supply",out_of_gas:"Out of gas",offline:"Offline",unknown:"Unknown"};
export default function StationPage(){
 const {id}=useParams<{id:string}>(); const [s,setS]=useState<S|null>(null),[user,setUser]=useState<string|null>(null),[msg,setMsg]=useState(""),[status,setStatus]=useState("available"),[price,setPrice]=useState(""),[queue,setQueue]=useState(""),[reports,setReports]=useState<R[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{const db=createClient();db.from("stations").select("*").eq("id",id).single().then(({data})=>{setS(data as S|null);setLoading(false)});db.from("station_reports").select("id,status,price_per_scm,queue_minutes,created_at").eq("station_id",id).eq("is_moderated",true).order("created_at",{ascending:false}).limit(5).then(({data})=>setReports((data||[]) as R[]));db.auth.getUser().then(({data})=>setUser(data.user?.id||null))},[id]);
 async function report(){if(!user){location.href="/auth";return}setMsg("");const {error}=await createClient().from("station_reports").insert({station_id:id,user_id:user,status,price_per_scm:price?+price:null,queue_minutes:queue?+queue:null});setMsg(error?error.message:"Report submitted for Earthoc moderation. Thank you.");if(!error){setPrice("");setQueue("")}}
 async function claim(){if(!user){location.href="/auth";return}const business=prompt("Business/operator name");if(!business)return;const phone=prompt("Contact phone number");const {error}=await createClient().from("station_claims").insert({station_id:id,user_id:user,business_name:business,phone});setMsg(error?error.message:"Station claim submitted for Earthoc approval.")}
 if(loading)return <main><div className="loadingState">Loading station information…</div></main>;
 if(!s)return <main><section className="panel"><h1>Station not found</h1><p className="muted">This station may no longer be available on the approved GasLink network.</p><Link href="/stations" className="primary">Back to Find CNG</Link></section></main>;
 const freshness=s.last_verified_at?new Date(s.last_verified_at).toLocaleString():"No verified update yet";
 return <main><header><Link href="/" className="brand"><span className="mark">G</span><div><b>GasLink</b><small>Station intelligence</small></div></Link><nav className="topNav"><Link href="/stations">Find CNG</Link><Link href="/trip">Trip planner</Link><Link href="/marketplace">Marketplace</Link><Link href="/services">Services</Link></nav><div className="headerActions"><BackButton fallback="/stations"/><Link href="/dashboard" className="ghost">Account</Link></div></header>
 <section className="stationDetailHero"><div className="stationDetailHeroInner"><div className="cardBadges"><span className={"status "+s.status}>{labels[s.status]||s.status}</span>{s.is_demo&&<span className="demo">Demo data</span>}{s.is_verified&&<span className="verifiedBadge"><ShieldCheck size={12}/> Verified station</span>}</div><h1>{s.name}</h1><p><MapPin size={17}/>{s.address}{s.city?", "+s.city:""}{s.state?", "+s.state:""}</p><div className="actionRow"><button className="primary" onClick={()=>window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.address),"_blank")}><Navigation size={17}/> Get directions</button><button className="secondary darkSecondary" onClick={claim}><Building2 size={17}/> Claim this station</button></div></div></section>
 <section className="stationDetailV2"><div className="stationMainColumn"><div className="stationFacts"><div><Gauge/><small>Price / SCM</small><strong>{s.price_per_scm!=null?"₦"+s.price_per_scm:"Not reported"}</strong></div><div><Clock3/><small>Estimated queue</small><strong>{s.queue_minutes!=null?s.queue_minutes+" min":"Unknown"}</strong></div><div><Clock3/><small>Operating hours</small><strong>{s.opening_hours||"Not reported"}</strong></div><div><ShieldCheck/><small>Last verified</small><strong>{freshness}</strong></div></div>
 <section className="infoCard"><div className="infoCardHead"><div><span className="eyebrow">Station information</span><h2>What drivers should know</h2></div></div><div className="infoRows"><div><span>Operator</span><b>{s.operator_name||"Not reported"}</b></div><div><span>Current status</span><b>{labels[s.status]||s.status}</b></div><div><span>Open now</span><b>{s.open_now==null?"Not reported":s.open_now?"Yes":"No"}</b></div><div><span>Vehicle compatibility</span><b>{s.vehicle_compatibility?.length?s.vehicle_compatibility.join(", "):"Not reported"}</b></div></div></section>
 <section className="infoCard"><div className="infoCardHead"><div><span className="eyebrow">Community intelligence</span><h2>Recent verified reports</h2></div><MessageSquare/></div>{reports.length? <div className="reportTimeline">{reports.map(r=><div className="reportItem" key={r.id}><span className={"status "+r.status}>{labels[r.status]||r.status}</span><div><b>{r.price_per_scm!=null?"₦"+r.price_per_scm+"/SCM":"Price not reported"}</b><span>{r.queue_minutes!=null?r.queue_minutes+" min queue":"Queue unknown"} · {new Date(r.created_at).toLocaleString()}</span></div></div>)}</div>:<div className="emptyInline">No moderated community reports yet.</div>}</section></div>
 <aside className="reportBox reportSticky"><div className="reportIcon"><MessageSquare/></div><h2>Report station conditions</h2><p className="muted">Help other drivers know before they go. Reports are reviewed before becoming trusted network information.</p><label>Availability<select value={status} onChange={e=>setStatus(e.target.value)}><option value="available">Available</option><option value="low_supply">Low supply</option><option value="out_of_gas">Out of gas</option><option value="offline">Offline</option></select></label><label>Current price / SCM<input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Optional"/></label><label>Estimated queue (minutes)<input type="number" value={queue} onChange={e=>setQueue(e.target.value)} placeholder="Optional"/></label><button className="primary fullButton" onClick={report}>Submit station report</button>{msg&&<div className="authMsg"><CheckCircle2 size={16}/>{msg}</div>}<small className="formNote">You must be signed in to submit a report.</small></aside></section></main>
}