"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {Wrench,ShieldCheck,Inbox,Plus} from "lucide-react";
export default function Provider(){const [p,setP]=useState<any>(null),[services,setServices]=useState<any[]>([]),[msg,setMsg]=useState(""),[enquiries,setEnquiries]=useState<any[]>([]),[showAdd,setShowAdd]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{const db=createClient();db.auth.getUser().then(async({data})=>{if(!data.user){location.href="/auth";return}const {data:x}=await db.from("service_providers").select("*").eq("user_id",data.user.id).maybeSingle();setP(x);if(x){const {data:y}=await db.from("service_offerings").select("*").eq("provider_id",x.id);setServices(y||[]);const {data:e}=await db.from("service_enquiries").select("id,message,phone,status,created_at,service_offerings(title)").eq("provider_id",x.id).order("created_at",{ascending:false});setEnquiries(e||[])}})},[]);
async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!p||busy)return;setBusy(true);setMsg("");const f=new FormData(e.currentTarget),title=String(f.get("title")||"").trim(),category=String(f.get("category")||p.provider_type),description=String(f.get("description")||"").trim();const {error}=await createClient().from("service_offerings").insert({provider_id:p.id,title,category,description,status:"pending"});setMsg(error?error.message:"Service submitted for review.");if(!error){e.currentTarget.reset();setShowAdd(false);const {data:y}=await createClient().from("service_offerings").select("*").eq("provider_id",p.id);setServices(y||[])}setBusy(false)}
return <main><header><Link href="/services" className="brand"><span className="mark">G</span><div><b>GasLink Provider</b><small>CNG services workspace</small></div></Link><div className="headerActions">{p&&<button className="primary" onClick={()=>setShowAdd(true)}><Plus size={17}/> Add service</button>}<BackButton fallback="/services"/></div></header>
<section className="operatorHero"><div><div className="eyebrow"><Wrench size={15}/> Provider workspace</div><h1>Manage your services and customer interest.</h1><p>Keep your GasLink service presence current, follow review status and respond to incoming demand.</p></div>{p&&<div className="operatorHeroStat"><small>Provider status</small><strong style={{fontSize:24,textTransform:"capitalize"}}>{p.verification_status}</strong><span><ShieldCheck size={14}/> Earthoc verification</span></div>}</section>
<section className="adminWrap operatorWrap">{p?<><div className="adminStats"><div><Wrench/><b>{services.length}</b><span>Service offerings</span></div><div><ShieldCheck/><b>{services.filter(x=>x.status==="approved").length}</b><span>Approved</span></div><div><Inbox/><b>{enquiries.length}</b><span>Customer enquiries</span></div><div><Wrench/><b>{services.filter(x=>x.status==="pending").length}</b><span>Awaiting review</span></div></div>
{showAdd&&<form className="enquiryForm" onSubmit={add}><h3>New service offering</h3><label>Service title<input name="title" required/></label><label>Category<input name="category" defaultValue={p.provider_type} required/></label><label>Description<textarea name="description" required/></label><div className="actionRow"><button className="primary" disabled={busy}>{busy?"Submitting…":"Submit for review"}</button><button className="secondary" type="button" disabled={busy} onClick={()=>setShowAdd(false)}>Cancel</button></div></form>}{msg&&<div className="authMsg">{msg}</div>}
<h2 className="adminSectionTitle">Your services <span>Publication pipeline</span></h2><div className="adminList">{services.map(x=><div key={x.id}><b>{x.title}</b><span>{x.category} · {x.status}</span></div>)}{!services.length&&<div className="emptyBox"><h2>No services published yet</h2><p className="muted">Add your first service offering and submit it for review.</p><button className="primary" onClick={()=>setShowAdd(true)}>Add first service</button></div>}</div>
<h2 className="adminSectionTitle">Customer enquiries <span>Incoming demand</span></h2><div className="adminList">{enquiries.map((e:any)=><div key={e.id}><b>{e.service_offerings?.title||"General service enquiry"}</b><span>{e.phone||"No phone"} · {e.status}</span><p>{e.message}</p></div>)}{!enquiries.length&&<div className="emptyBox"><Inbox/><h2>No customer enquiries yet</h2><p className="muted">New enquiries will appear here as customers discover your approved services.</p></div>}</div></>:<div className="emptyBox" style={{maxWidth:760,margin:"20px auto",textAlign:"center",padding:48}}><Wrench size={36}/><h2>Join the verified CNG service network</h2><p className="muted">Create a provider profile, complete Earthoc verification and publish services customers can discover.</p><Link className="primary" href="/services/join">Create provider profile</Link></div>}</section></main>}