"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import BackButton from "@/components/BackButton";
import {createClient} from "@/lib/supabase/client";
import {ShieldCheck,Wrench} from "lucide-react";
const types=["Conversion Centre","CNG Technician / Installer","Maintenance & Repair","Inspection & Testing","Station Engineering / EPC","Fleet Conversion Support","Emergency / Breakdown Support"];
export default function Join(){const [uid,setUid]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);useEffect(()=>{createClient().auth.getUser().then(({data})=>{if(!data.user)location.href="/auth";else setUid(data.user.id)})},[]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const {error}=await createClient().from("service_providers").insert({user_id:uid,business_name:String(f.get("business_name")),provider_type:String(f.get("provider_type")),phone:String(f.get("phone")),email:String(f.get("email")),address:String(f.get("address")),city:String(f.get("city")),state:String(f.get("state")),description:String(f.get("description"))});setMsg(error?error.message:"Provider profile submitted for Earthoc verification.");if(!error)e.currentTarget.reset();setBusy(false)}
return <main><header><Link href="/services" className="brand"><span className="mark">x</span><div><b>CNGx</b><small>Service network</small></div></Link><BackButton fallback="/services"/></header><section className="marketHero"><div className="eyebrow"><Wrench size={15}/> CNG service network</div><h1>Turn your CNG expertise into trusted visibility.</h1><p>Join the directory for conversion, maintenance, inspection, engineering and fleet-support providers. Profiles become public only after verification.</p><div className="marketTrustRow"><span><ShieldCheck/> Provider verification</span><span>Specialist directory</span><span>Customer enquiries</span></div></section>
<section className="businessGrid"><div className="businessIntro"><span className="eyebrow">PROVIDER ONBOARDING</span><h2>Build a profile customers can trust.</h2><p>Tell us who you are, where you operate and what you do. Verification helps keep the CNGx service network useful and credible.</p><div className="businessSteps"><div><b>01</b><span>Submit your business and service information.</span></div><div><b>02</b><span>Earthoc reviews the provider profile.</span></div><div><b>03</b><span>Verified providers can publish services and receive enquiries.</span></div></div></div>
<form className="businessForm" onSubmit={submit}><label>Business / provider name<input name="business_name" required/></label><label>Provider type<select name="provider_type">{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Phone<input name="phone" required/></label><label>Email<input name="email" type="email" required/></label><label className="wide">Address<input name="address" required/></label><label>City<input name="city" required/></label><label>State<input name="state" required/></label><label className="wide">About your CNG services<textarea name="description" required placeholder="Describe your capabilities, typical customers, equipment or certifications where relevant."/></label><div className="formSummary wide"><ShieldCheck size={17}/> Provider verification is required before public listing.</div><button className="primary wide" disabled={busy}>{busy?"Submitting…":"Submit provider profile for verification"}</button>{msg&&<div className="authMsg wide">{msg}</div>}</form></section></main>}